# Generated by Django 2.1.5 on 2019-09-07 13:29

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=40)),
                ('contenu', models.TextField(default='', unique=True)),
                ('date_post', models.DateTimeField(auto_now=True, verbose_name='Date dernière modification')),
                ('titre', models.CharField(max_length=100, unique=True)),
                ('introduction', models.TextField(null=True, unique=True, verbose_name='Intro')),
                ('vue', models.ImageField(default=False, upload_to=blog.models.rename_article_vue, verbose_name='Image du post')),
                ('valide', models.NullBooleanField(default=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['categorie', 'date_post'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Categorie')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categorie'),
        ),
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('slug', 'parent')},
        ),
    ]
